# https://github.com/0916dhkim/vscode-devcontainer-tutorial/blob/master/.devcontainer/docker-compose.yml
version: "3"
services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sleep infinity
    user: root
    ports:
      - 4000:4000
    volumes:
      - ..:/workspace